### ISSUE TITLE
Where is the water?

### ISSUE THREAD

**Issue by BaiGave** [Sam54123/mc-world-export#8]
This mod is very good，but I have some problems。I can't find water in blender；And can you add an option to cull underground caves？When the number of faces reaches tens of millions, blender will be very stuck..........（Translated by Google）

**Comment by Sam54123** [comment]
Liquids such as water and lava are currently unsupported due to implementation difficulties, but they're a priority on the to-do list. For now, simple bodies of water such as lakes should be [manually created in Blender](https://youtu.be/8m6oq_b9if0).

As for cave culling, the implementation details of that are quite complex and it likely won't be added for a while. Additionally, due to the way the Blender addon is coded, cave geometry contributes little in regards to performance. The main factor is the sheer volume of the exported world. A far more effective optimization would be to raise the lower depth during export to the minimum Y value required, removing the caves from the file all together.

Hope this helps!
