### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by BaiGave** [Sam54123/mc-world-export#9]
Blocks don't seem to break animations.
Water doesn't seem to be showing properly.
Is there a way to display more Chunks, such as using the GreedyMesh algorithm to reduce the faces, and reduce the detail level of distant blocks？
The modded creatures seem to be gone, but most of the modding blocks work fine.

**Comment by Sam54123** [comment]
Thanks for your feedback! Here are my responses in order:

> **Blocks don't seem to break animations.**

Block break animations are quite difficult because, similar to particles, they get a dedicated render pipeline in the Minecraft client which is not trivial to port to Blender. This is something I might look into in the future.

> **Water doesn't seem to be showing properly.**

Liquids such as water and lava are currently unsupported due to implementation difficulties, but they're a priority on the to-do list. For now, simple bodies of water such as lakes should be [manually created in Blender](https://youtu.be/8m6oq_b9if0).

> **Is there a way to display more Chunks, such as using the GreedyMesh algorithm to reduce the faces, and reduce the detail level of distant blocks？**

Although it's possible to find a way to export outer chunks in a more efficient manner, due to the way the `.replay` format works, it's not as simple as reducing the vertex count through GreedyMesh. For now, if you're having trouble with your export size, I recommend exporting the outer chunks manually using Mineways and importing them into Blender separately. Or do what I do and fake it using screenshots on planes.

> **The modded creatures seem to be gone, but most of the modding blocks work fine.**

*Modded creatures are not currently supported*. This is due to the fact that, instead of using a standard model system, Mojang decided to code Minecraft's engine such that each entity writes *directly* to viewport vertex buffers every frame, leaving no model to extract. The only way around this problem is to write a "[model adapter](https://github.com/Sam54123/mc-world-export/blob/main/doc/entity_export_design_doc.md)" for each entity that might be exported into a replay, and although much of this can be generalized into universal code, the fact remains that a model adapter must be registered for every entity class.

In the future, there are plans to write a model adapter generation system, which will attempt to reverse-engineer the entity rendering code and create a model adapter from it (including modded entities). At the moment, however, model adapters must be written manually. Blocks do not share this issue because they use a standardized model system internally.

Hope this helps!
